# Generated by Django 3.1.1 on 2020-09-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.CharField(blank=True, default='', max_length=50)),
                ('longitude', models.CharField(blank=True, default='', max_length=50)),
                ('api_city_id', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_id', models.CharField(blank=True, default='', max_length=10)),
                ('weather_main', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, default='', max_length=20)),
                ('feels_like', models.CharField(blank=True, default='', max_length=20)),
                ('temperature_max', models.CharField(blank=True, default='', max_length=20)),
                ('temperature_min', models.CharField(blank=True, default='', max_length=20)),
                ('pressure', models.CharField(blank=True, default='', max_length=20)),
                ('humidity', models.CharField(blank=True, default='', max_length=20)),
                ('recent', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.weather')),
            ],
        ),
    ]
