# Generated by Django 3.1 on 2020-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.CharField(blank=True, default='', max_length=50)),
                ('longitude', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
